CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(100),
  phone_number VARCHAR2(15),
  PRIMARY KEY (id)
);

INSERT INTO users (name, phone_number)
VALUES ('Abhijeet', '+919075180122');

COMMIT;
